# Generated by Django 6.0.3 on 2026-05-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.subject'),
        ),
    ]
